version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=startdb
      - POSTGRES_USER=start
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
