version: '3.8'

services:
  api:
    build:
      context: ../
      dockerfile: ../Dockerfile
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=startdb
      - POSTGRES_USER=start
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
