version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=startdb
      - POSTGRES_USER=start
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_start
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  postgres_data:
